server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/boardcrudex?characterEncoding=UTF-8&&serverTimeZone=UTC
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        connection:
          charSet: UTF-8
    database-platform: org.hibernate.dialect.MariaDB10Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    sql: debug
    type: trace

